### ISSUE TITLE
Branch searchfunctie broken

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#104]
When I load the data directory of De Stadsbron, all css is lost. No styling remains.

**Comment by matthijskooijman** [comment]
Do you mean *all* CSS? Or all CSS related to search? The latter is of course expected, if you overwrite all CSS with the stadsbron version...

**Comment by matthijskooijman** [comment]
I'm going to close this, as this is not a bug in merged master code, but only exists in a work-in-progress branch. It might be better to discuss this at the PR about this branch, in #100.
