### ISSUE TITLE
impossible to add links in fields "bijsluiter" and "bronnen"

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#118]
especially in Bronnen it is handy to be able to make hyperlinks.

**Comment by tammoterhark** [comment]
Related to: https://github.com/PlanBCode/hypha/issues/113

**Comment by matthijskooijman** [comment]
I think the name for these fields in code and in the English version is "sources" and "method".

AFAICS you can already add links, by typing raw HTML. This is not ideal, so a soultion probably means a WymEditor should be used on these fields instead.
