### ISSUE TITLE
Improve notification when an article changed status

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#124]

**Comment by matthijskooijman** [comment]
Turns out that *everybody* already receives these notifications, but because the subject line is too generic and it is hard to filter these messages. Improving the subject would help.

**Comment by matthijskooijman** [comment]
See #183 for some examples on how to improve the notification mails being sent (in a nice separated subject and body translated string, and with variables inside the string).

**Comment by matthijskooijman** [comment]
This is fixed in #183.
