### ISSUE TITLE
New page dialog includes "settings" pagetype

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#146]
This is probably a side effect of a697fc2a56b09ebec3cfe48231b608ff63493d8d

I'm not sure what the best fix is. Perhaps settings.php should be moved out of datatypes, since it is not really a datatype, only a (special) page type I believe?

**Comment by giplt** [comment]
I suggest it to be a reserved datatype name and hardcode its exclusion from the new page dialog
