### ISSUE TITLE
Feature: Make default page type configurable

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#151]
The default page type (e.g. the datatype that is preselected when you click "new page") is now (I believe) hardcoded to be webpage (text). However, some instances, use another type more intensively (e.g. article in the stadsbron) and it would be helpful to users to preselect that type. This could be simply a pagetype dropdown in the settings page (similar to the default language).

#137 also suggests that such a default pagetype could be expanded into an orderable list of pagetypes (so you can change the default, but also the order), but that would require more effort for less gain, so it seems better to implement just the default selection first.

**Comment by tammoterhark** [comment]
Currently: 

![de stadsbron test 1](https://user-images.githubusercontent.com/6483317/51425240-9c8f4900-1bd9-11e9-9692-c29aab0b114c.png)
