### ISSUE TITLE
Wish to be able to override publication cycle

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#155]
De Stadsbron editors want to be able to override the approvement cycle for articles (currently videos), so they can be published right away.

Idea: give person that entered the video the ability to check "Override approvements" whereby the article is published as soon as one other person has approved it. So no 3 approvements and no publishing after 3 approvements. IMHO: at least two sets of eyes need to have seen the article: the original poster and at least one other.

**Comment by giplt** [comment]
I think this is a bad idea as it undermines the very idea of peer review. If needed an article can simply be published in a webpage. However, this alters the ethics of the publication process which should be solved by discussion among the editors rather than by adding perverse technology.
