### ISSUE TITLE
Title ending in dot (.) produces "difficult" link

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#173]
Please see:

http://destadsbron.nl/nl/Houzee._Triomf_voor_de_NSB.

This link conflict with some editors that omit the ending dot. For example when people want to Twtter about this.

**Comment by matthijskooijman** [comment]
A quick fix would be to replace dots with _, just like we do for spaces (and probably other characters). One point of note is that existing links with dots could break. This could be fixed by normalizing the request URL before matching against normalized page titles, but I'm not sure how this works in the code now.

**Comment by tammoterhark** [comment]
This issue may also be related to:
https://github.com/PlanBCode/hypha/issues/27

**Comment by tammoterhark** [comment]
One of the creatives in De Stadsbron made the following link:
http://www.destadsbron.nl/nl/Wat_tussen_de_oren_zit...
which give a problem when wanting to post this on FaceBook or Twitter.
Just omitting dots and other special characters and replacing spaces with a hyphen would really help.

From: https://www.werockyourweb.com/url-escape-characters/


> Good Coding Practice
> It is good coding practice to avoid the need for URL escape characters. As a rule of thumb, avoid using the special characters above when formulating a URI string (filename), and I recommend using the hyphen (-) instead of the underscore (_) (as all search engines recognize the hyphen as a space separator, but the same is not true for the underscore; and older browsers do not correctly interpret the underscore in CSS). If you must use the above characters make sure to escape them using the above escape characters so when the browser parses your code it will not misinterpret the link. It’s important to note that these URL escape characters differ from HTML escape characters.
>

**Comment by matthijskooijman** [comment]
A solution to this problem suggested by the URL specifications is to enclose URLs in angled brackets. That helps processors to detect where a url starts and stops. I'm not sure if Facebook and Twitter support this, but github does. e.g:

<http://www.destadsbron.nl/nl/Wat_tussen_de_oren_zit...>

We should also fix this in Hypha, but this might help to at least publish these existing links right now.

**Comment by matthijskooijman** [comment]
A more generic fix for this would be to allow editing the title and url/name separately, which is #78.
