### ISSUE TITLE
De-wikify links to images in mail from mailinglist

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#179]
When sending mail from mailinglist, in mail that contains images, the links to the images stay internal links. This results in no-show of images in mails.

**Comment by matthijskooijman** [comment]
What do you mean by "internal links" exactly? Links with a relative path (not including the domain)? Or actual wikified links like "hypha:123abc"?

**Comment by tammoterhark** [comment]
Links to a relative path.

**Comment by matthijskooijman** [comment]
This might be the same or similar to #189.
