### ISSUE TITLE
Internal links always show pagename

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#186]
```
<p>Hier een zin met een interne link. <a href="hypha:5b3b663ea3a96">Klik hier</a></p>
<p>Hier een zin met een externe link. <a href="http:://www.toolsforresearch.com">Klik hier</a></p>
```
Shows on the screen like:

Hier een zin met een interne link. Armandomuseum
Hier een zin met een externe link. Klik hier

**Comment by tammoterhark** [comment]
http://test.destadsbron.nl/nl/Test_van_Tammo

**Comment by tammoterhark** [comment]
Getest op artikel en webpagina, beiden zelfde resultaat.

**Comment by matthijskooijman** [comment]
Confirmed, seems that my latest fix for dewikify now changed from working for text-links only, to working for non-text-links only.. I'm looking at a fix.
