### ISSUE TITLE
comment confirmation broken

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#194]
Bug in the system where readers can leave a comment. They do not get a message that tells them to go to their email and confirm they sent the comment, nor do they get the email.

**Comment by matthijskooijman** [comment]
The message was misplaced by @giplt, see https://github.com/PlanBCode/hypha/issues/99#issuecomment-455312989

As for not getting the e-mail, you mentioned this on Riot, but neither me or Laurens could reproduce this. Did you try with a different e-mail address perhaps?
