### ISSUE TITLE
Notify (non-logged in) visitors of followup comments

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#201]
When "Reader A" (not a user in Hypha) has left a comment and "Reader B" reflects on that, I would expect that (next to the Hypha users, that do get a notification), "Reader A" is notified, but this is not the case.

When we want to encourage dialogues, this is a necessary addition to the commenting/notifications mechanism.

**Comment by tammoterhark** [comment]
In general:
when commenting, I would like to propose a checkbox (checked by default) that indicates:
"I want to be informed of other comments on this page"

Extra: And in the notification mail that the person receives a link to unsubscribe for notifications on the article.

**Comment by matthijskooijman** [comment]
This is covered in in #176 already, but it seems reasonable to implement this separately from notifications to logged-in users, so let's keep this one open for that option.

**Comment by matthijskooijman** [comment]
This is implemented in #281. There might be room for improvement, but that would probably be subject of a different issue (there's nothing specific left to implement in this issue), so I'm closing this one.
