### ISSUE TITLE
Numbers are being encoded as telephone numbers

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#231]
Source: http://destadsbron.nl/nl/column_provincie

![De Stadsbron (10)](https://user-images.githubusercontent.com/6483317/54374842-4215e480-4680-11e9-9216-526ae7171108.png)

**Comment by matthijskooijman** [comment]
I highly suspect that this is not something Hypha does (we do not handle tel: urls anywhere), so I suspect this is either the author's browser, or whatever source he has copied this text from, that introduces these links. It would be good to know a bit more about the process that lead to this post?

**Comment by tammoterhark** [comment]
Yes, browser issue.
