### ISSUE TITLE
Uploading invalid image does not show error

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#234]
When uploading an invalid image through the wymeditor image upload, no error is shown. Instead, the upload button remains at "Uploading..." indefinitely.

In the background, a POST request is made to `/upload/image` which returns a 200 and the following content:

    <script language="javascript" type="text/javascript">window.top.window.uploadResponse('~Invalid image file, must be a valid image less than 50M');</script>

The javascript console shows:

    TypeError: window.top.window.uploadResponse is not a function[Learn More] image:1:1
    TypeError: response is null[Learn More] jquery.wymeditor.image_upload.js:42:5

**Comment by tammoterhark** [comment]
It would be great if this bug was solved, since users of De Stadsbron just don't upload images anymore, they just send them to Guus.

So please: either scale the images when possible or give good error message.

**Comment by matthijskooijman** [comment]
@RoukePouw has suggested he might look at this, so I'm assigning him for now.

**Comment by RoukePouw** [comment]
In Safari uploading an  image through the WY** editor fails entirely. Without errors :-(

When I edit the text, add an image, the image does not show and the text is reset to its original content.

**Comment by RoukePouw** [comment]
a mentioned before the problem lies with:
`window.top.window.uploadResponse(\''.$response.'\');`

 I can't find any documentation online, so I think `uploadResponse` is not a standard part of the window object. But I can't find any definitions for a custom `uploadResponse` function? 

Is there perhaps some code missing?

**Comment by matthijskooijman** [comment]
Ah, seems this code was accidentally removed during a wymEditor upgrade. See https://github.com/PlanBCode/hypha/commit/75b2242db7f364680c66bb8c51c87bc7ea373368#diff-b65d5cb3f7c6cffa323982c5f3501ea0 (the change is in editor.php, which is hidden by default).

The original code was:

```
				+ "<script type='text/javascript'>\n"
				+ "function uploadResponse(response) {\n"
				+ "	if (response.charAt(0) == '~') alert(response.substring(1));\n"
				+ "	else {\n"
				+ "		window.opener.WYMeditor.INSTANCES[0].insert('<img id=\"hyphaInsertImage\" alt=\"' + jQuery(document.body).find('input[name=wymAlt]').val() + '\" title=\"' + jQuery(document.body).find('input[name=wymTitle]').val() + '\"/>');\n"
				+ "		jQuery(window.opener.WYMeditor.INSTANCES[0]._doc.body).find('#hyphaInsertImage').attr('src', '<?=$rootUrl?>' + response);\n"
				+ "		jQuery(window.opener.WYMeditor.INSTANCES[0]._doc.body).find('#hyphaInsertImage').removeAttr('id');\n"
				+ " }\n"
				+ "	window.close();\n"
				+ "}\n"
				+ "<\/script>\n"
```

I'm not sure if this still applies entirely, since I think this also *inserts* the image into the editor, which is now handled differently (through the existing insert image wymeditor dialog, I think) and that part still works. Also, I'm not sure if the `~` prefix for errors is still used by the backend, but if so, I don't like it that much (would rather see that the backend would return a JSON message with a status, error message and/or filename field or something like that, or maybe communicatie the status through the HTTP status code instead (e.g. generate 500 when an upload is too big).

**Comment by matthijskooijman** [comment]
Ter leering ende vermaeck: I found this commit using `git log -G uploadResponse`

**Comment by RoukePouw** [comment]
Thanks!

Not sure what my next action should be now. Should I spend time to get in working in the front-end or should this wait until back end upgrades you suggested have been made?

**Comment by matthijskooijman** [comment]
Did you check what the backend returns now? Maybe the `~`-prefix stuff already has been replaced by something else?

**Comment by RoukePouw** [comment]
`window.top.window.uploadResponse('~Ongeldige afbeelding, moet een geldige afbeelding zijn minder dan 32M')`

( I uploaded a 1kb .txt file )

**Comment by RoukePouw** [comment]
Looks like there are three errors like this (in Dutch and English) 
```
"too-big-file" => "~Error: file must be less than ",
		"invalid-image-file" => "~Invalid image file, must be a valid image less than ",
		"server-error" => "~Server error, failed to move file",
```

```
pages.php :328
if(!$_FILES['uploadedfile']) $response = __('too-big-file').ini_get('upload_max_filesize');
pages.php:332:
if(!$_FILES['uploadedfile']) $response = __('too-big-file').ini_get('upload_max_filesize');
pages.php:356
$response = __('server-error');
```

And a bonus error which can be thrown, but does not seem to be defined:

```
pages.php:347
	$response = __('server-error-resize-image');
```

I would suggest a function to wrap json around the messages: 
```
$response = wrapErrorInJson(__('server-error-resize-image')); 
```

which would return something like `{"error":true, "message":"Oh no, too big!"}`  (better phrased etc ;-) ) 

But I'm not yet sure what this would break elsewhere (does other stuff rely on the ~  message ? )

**Comment by RoukePouw** [comment]
I've made a minimal PR that reinstate the uploadResponse function. 

https://github.com/PlanBCode/hypha/pull/308

This could be tidied up and then merged to provide some improvement. Or do we want to include back end upgrades in this PR/issue as well?
