### ISSUE TITLE
Add mailing list gives error 500

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#25]
I tried to define a mailing list. First screen is OK, after save I get an error 500.

**Comment by matthijskooijman** [comment]
Turns out this only happens when the description is empty. Error log shows that a document without a `documentElement` is passed to `wikifiy()` which then crasehs.

**Comment by matthijskooijman** [comment]
@laurensmartina, can you have a look at this?

**Comment by tammoterhark** [comment]
Overgebracht naar hypha-improvements.
