### ISSUE TITLE
Spelling errors in help text

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#266]
![hyphahelp](https://user-images.githubusercontent.com/6483317/64530508-9affc600-d30d-11e9-965b-556145bddde8.png)

Improvement:
-------------------------------------
Dit is een platform voor constructieve discussie, daarom hebben we wat regels opgesteld voor alle commentatoren.
1. Overweeg of uw commentaar nieuwe informatie of overwegingen aan de discussie toevoegt. 
2. Houd de toon beschaafd.
3. Maak uzelf bekend met uw volledige naam. De redactie behoudt zich het recht voor om uw bijdrage te verwijderen of uw identiteit bekend te maken als u dat zelf niet doet.
-------------------------------------

**Comment by matthijskooijman** [comment]
This was fixed in #279.
