### ISSUE TITLE
Add "(TEST)" in newsletter title when sent in testmode

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#269]
when a newsletter is sent to testers, they can not tell if it is the final newsletter or a draft that they have to check.

**Comment by dianawi** [comment]
suggested text to add in the subject: testnieuwsbrief, graag controleren!/ newsletter test, please check!

**Comment by dianawi** [comment]
Done by Laurens, no pull request yet

**Comment by matthijskooijman** [comment]
According the the PR and the project board, this was done in #277, so closing this issue.
