### ISSUE TITLE
Renaming a page does not redirect to new url

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#27]
After renaming a page, the url still points to the old name, which gives an empty response (or error, not sure).

**Comment by tammoterhark** [comment]
Overgebracht naar hypha-improvements. Kan hier gesloten worden.

**Comment by tammoterhark** [comment]
* define new page. Title: "Black" 
* save page
* see in index: page with title "Blacl"  exits.
* open page "Black" for edit.
* rename: title now becomes "White"
* save page
* visit index: page is still called " Black"

**Comment by matthijskooijman** [comment]
The original issue is fixed, so I'm closing this. The issue that @tammoterhark describes (that renaming pages does not work at all) might still exist, but I suspect it is specific to articles.
