### ISSUE TITLE
H1 only once on each page

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#30]
For better SEO `<h1>` should occur only once per page. Since it is used for the page-title, it should not appear in the editor as a tag that can be chosen.

**Comment by matthijskooijman** [comment]
Isn't a better fix for this to use the HTML5 `<title>` tag?

**Comment by tammoterhark** [comment]
I believe `<title>` is metadata

**Comment by matthijskooijman** [comment]
W00ps. I remember HTML5 added some additional tags for this kind of thing. I think of those, `<header>` would be better? https://www.w3schools.com/tags/tag_header.asp

**Comment by tammoterhark** [comment]
And only one `<h1>` in that header (and preferablyu on the whole page.

**Comment by matthijskooijman** [comment]
I was sugggesting to replace the `<h1>` with `<header>`, and then allow use of the `<h1>` tag inside the page multiple times.

**Comment by tammoterhark** [comment]
Technically speaking that is no problem. But for SEO only one `<h1>` per page is preferable.

**Comment by matthijskooijman** [comment]
I don't really know about SEO, so I'll assume that from you. So that just means to disable the H1 in the editor?

**Comment by tammoterhark** [comment]
Yes, just to make people not use `<h1>` for making a text larger.

**Comment by tammoterhark** [comment]
Overgebracht naar hypha/improvements
