### ISSUE TITLE
Mark displayed excerpt as such

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#303]
Currently, the excerpt of an article is shown to logged in users. However, it is not entirely clear that it is the excerpt, and that it is not shown to non-logged-in-users.

@tammoterhark will have a look if we can fix this using CSS for the de Stadsbron, but also the default Hypha CSS.

**Comment by tammoterhark** [comment]
For De Stadsbron, comments welcome

![image](https://user-images.githubusercontent.com/6483317/81183990-240bf180-8fb0-11ea-9d15-46c96372dba3.png)

**Comment by tammoterhark** [comment]
This is how it could look in default theme

![image](https://user-images.githubusercontent.com/6483317/81184751-10ad5600-8fb1-11ea-906a-0049696b8158.png)

**Comment by tammoterhark** [comment]
Can someone please add the following lines to the hypha.css of the default theme? This would take me more than 1 hour, considering GIT etc.

`.excerpt{
	background: lightyellow;
	padding: 10px;
	border: 1px var(--orange);
	margin-top: 15px;
}

.excerpt::before{
	content: "Uittreksel voor de voorpagina: ";
	color: red;
	display: block;
	font-size: 16px;
	font-weight: bold;
	margin-top: 0;
	margin-bottom: 10px;
}

.excerpt::after{
	content: "Alleen zichtbaar als je ingelogd bent";
	color: red;
	display:block;
	font-size: 12px;
	font-weight: normal;
	margin-top: 10px;
	margin-bottom: 0;
}`

**Comment by tammoterhark** [comment]
This is now for NL only. If needed braoder, we need code changes. Maybe not needed at this moment.

**Comment by matthijskooijman** [comment]
Looks good!

> This is now for NL only. If needed broader, we need code changes. Maybe not needed at this moment.

Yeah, for the default Hypha theme translations would maybe be nice (in which case the text must be added by the code, but then be replaced by CSS if needed?).

> Uittreksel voor de voorpagina: ";

This might not be generally true: It is currently only used in tag index pages, in the future probably also in things like search pages, etc. So maybe this could just say "Excerpt used in page lists" or something (or maybe just "Excerpt") in the default theme, and then be overridden in CSS with something more appropriate for the stadsbron?

**Comment by tammoterhark** [comment]
Please add the following code (for the moment). Later to be coded. Only used Dutch for now. I leave that to be fixed by higher intelligence.

body.type_peer_reviewed_article .excerpt{
	background: lightyellow;
	padding: 10px;
	border: 1px var(--orange);
	margin-top: 15px;
}

body.type_peer_reviewed_article .excerpt::before{
	content: "Uittreksel: ";
	color: red;
	display: block;
	font-size: 16px;
	font-weight: bold;
	margin-top: 0;
	margin-bottom: 10px;
}

body.type_peer_reviewed_article .excerpt::after{
	content: "Alleen zichtbaar als je ingelogd bent";
	color: red;
	display:block;
	font-size: 12px;
	font-weight: normal;
	margin-top: 10px;
	margin-bottom: 0;
}

**Comment by tammoterhark** [comment]
Just to be clear: add to hypha.css in the default theme....

**Comment by matthijskooijman** [comment]
@tammoterhark, I noticed that this also produces a notice for empty excerpts, which maybe looks a bit weird? e.g.: https://destadsbron.nl/nl/ColumnMaarten3

![image](https://user-images.githubusercontent.com/194491/81416694-5cdfce00-914a-11ea-9235-5077d22fb900.png)

I initially thought to just omit the excerpt div entirely when it is empty, but you *might* want to use CSS to highlight the lack of an excerpt maybe?

So maybe hide the after/before (or the entire thing) using CSS and the `:empty` selector?

OTOH, if these before/after things are to be translateable in the default theme, they must be added in the HTML itself, so they it seems again weird to add them when the excerpt is empty (which would suggest just removing the entire thing when it is empty).

What would be a good way to add these prefixes in HTML anyway?

 - Just inside the div is obvious, but maybe not easy to style:
        <div class="excerpt"><span class="prefix">Excerpt, only visible when logged in</span>Excerpt here</div>
 - Dangling before the excerpt, probably not easy to style either:
       <span class="prefix">Excerpt, only visible when logged in</span><div class="excerpt">Excerpt here</div>
 - So maybe add a container?
       <div class="excerpt-container"><span class="prefix">Excerpt, only visible when logged in</span><div class="excerpt">Excerpt here</div></div>

I tend towards the latter, since that makes it easy to just hide `.excerpt-container prefix` in CSS and replace it by something else (as you do now, and similar to the prefix for the tag list).

Then, when the excerpt is empty, we could just generate an empty container:

    <div class="excerpt-container"></div>

Which is not shown by default, but still allows marking it with css (`.excerpt-container:empty` or something).

@tammoterhark, how does the last bit look to you?

**Comment by matthijskooijman** [comment]
This was fixed in 3a83df8d8917e4ef044ceaad51a82d765e3edfa8.
