### ISSUE TITLE
Automatic completeness of articles before starting review

### ISSUE THREAD

**Issue by matthijskooijman** [PlanBCode/hypha#304]
Currently, excerpts in article are completely optional. It would be good if an excerpt is required to move the status from draft to ready for review.

I can imagine a few options:
 1. Show message *instead* of a "start review" button.
 2. Leave out the button and show a message "No excerpt yet, cannot start review until one is added" at the place where the excerpt
 3. Show an error message when clicking "start review" without an excerpt.

**Comment by RoukePouw** [comment]
4. disable the button and show a message "No excerpt yet, cannot start review until one is added" at the place where the excerpt?

This way you don't hide parts of the user interface. In my opinion it's nice to keep buttons where there are so you don't get "lost".

**Comment by matthijskooijman** [comment]
This was discussed today, disabling the "start review" button and showing a message right there seemed promising. One other thought was to maybe show a checklist of things that need to be done before starting review (e.g. the article must also not be empty, probably not the method either, maybe the sources can be allowed to be empty). @tammoterhark will have a look at this and make a mockup of how this could work.

**Comment by matthijskooijman** [comment]
Today in the Stadsbron meeting, one additional check came up: Check requirements on configured tags (this probably means at least one tag, maybe selected from a specific subset of tags). This is hard to hardcode (the Stadsbron requires this, other instances might not), so this might need to be configurable.

**Comment by matthijskooijman** [comment]
This might be something we should fix before auto-generating the Stadsbron homepage, to prevent incomplete articles (e.g. no excerpt or image) from showing up on the homepage.

**Comment by matthijskooijman** [comment]
I've implemented this now, PR coming up. I ended up hiding the button rather than disabling it, since that was easier to implement (setting disabled on the button requires some DOM trickery and additional CSS to show it as disabled, and might need a title tag or so for additional feedback, etc.).
