### ISSUE TITLE
Install new hypha fails (probably because of empty lang dropdown)

### ISSUE THREAD

**Issue by RoukePouw** [PlanBCode/hypha#306]
when creating a hypha.php to download the subsequent form has an empty language dropdown. On send a blank screen is shown and the install did not succeed

**Comment by matthijskooijman** [comment]
When you get the blank screen, is there any error in your webserver error log?

**Comment by RoukePouw** [comment]
Not sure, I'll check. 

But I think this is the culprit 

` `` 
          case 'system/languages/languages.json': return file_get_contents('system/languages/languages.json');
```

**Comment by RoukePouw** [comment]
My current understanding:

Advanced : run from git repo

- no problems, because 'system/languages/languages.json' is available

Basic  : run from downloaded hypha.php

- Problem : because 'system/languages/languages.json' is not available

- Possible solution 1: add hardcoded fallback value
- - pro: quick and easy
- - con: additions/changes to languages will need to be synced manually
- Possible solution 1b: utilize some form of metadev (build script?) to add hardcoded values automaticcaly into the file
- - pro: no need for manually syncing (single source of truth)
- - con: not sure if there's plumbing for this?

**Comment by matthijskooijman** [comment]
> Possible solution 1: add hardcoded fallback value

I think this is what we had originally when running from git (en only), and tried to fix in #252.

> Possible solution 1b: utilize some form of metadev (build script?) to add hardcoded values automaticcaly into the file

This is *exactly* what the hypha.php building already should do. When you download a hypha.php file, it will have the contents of all other php files embedded. The idea is that the contents of the `data()` function is replaced by a a switch with all the contents of these files, *including* the languages.json file. So this line:

    case 'system/languages/languages.json': return file_get_contents('system/languages/languages.json');

Is just a place holder when running from git directly, in a downloaded hypha.php, that line should have been replaced by file contents for all relevant files.

However, it sounds like that entire thing is broken, if that line is still present in your generated hypha.php?

**Comment by RoukePouw** [comment]
Turns out it was some bad regex. I think in this context `^` searches from start of entire string, not start of line

**Comment by RoukePouw** [comment]
Looks like it was either an error on my end or a fluke. (Reference: https://github.com/PlanBCode/hypha/pull/307 )

Closing this
