### ISSUE TITLE
Link in comment not interpreted right.

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#380]
Article: https://www.destadsbron.nl/nl/Zorgomtegenmacht
Comment by Tammo
Link: https://www.trouw.nl/opinie/we-moeten-de-overheid-juist-wantrouwen~b1592127/ 
Interpreted as: https://www.trouw.nl/opinie/we-moeten-de-overheid-juist-wantrouwen

![image](https://user-images.githubusercontent.com/6483317/118552653-8240e800-b75f-11eb-9137-e4dd87746f76.png)

**Comment by matthijskooijman** [comment]
Gefixt en live gezet, dus link werkt nu naar behoren.

**Comment by tammoterhark** [comment]
Top!
