### ISSUE TITLE
Feature request: write tags as classes in body

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#381]
If you add the tags of the page also as classes in the body tag, this will give you the opportunity for easier styling of pages that have tags like:
"Opinie"
"Stadsrand"

With that pages like "Opinie" can be given an alternative look, distinguishing them from "normal" articles.

**Comment by matthijskooijman** [comment]
@tammoterhark This was implemented and is now live on destadsbron.nl, let me know if this is what you need.

This now adds two classes for each tag: With the (rather cryptic) id of the tag, and the label. The id is more stable across changes to tag names and translations (though neither is currently implemented), the label is easier to read. For the stadsbron, lacking translated pages and tags, I guess just using the labels is fine (makes for easier to read CSS files).

**Comment by tammoterhark** [comment]
True, thank you.
