### ISSUE TITLE
Friendly manual

### ISSUE THREAD

**Issue by giplt** [PlanBCode/hypha#385]
Write a friendly installation manual, guiding aspiring user-communities with the deployment of their hypha instance:
- Installation
- Upgrades
- User manual
- Community tech support: Element room?
- ...

**Comment by tai271828** [comment]
I installed `hypha` from scratch with the latest codebase in this git repository and the download from http://hypha.net/hypha.php on Ubuntu 18.04. I guess I can update README and pages like `http://hypha.net/en/install` later on. Feel free to assign this issue to me if you don't mind.


The list pops up in my mind that I can help and improve:
- [ ] README
- [ ] http://hypha.net/en/install
- [ ] http://hypha.net/en/server_setup
- [ ] http://hypha.net/en/server_setup_linux


Git repository (hash 42bcce5ac3e07e19dd412d239549adc5fdb62191 )
![Selection_681](https://user-images.githubusercontent.com/3217432/155632536-8a23c628-267c-44b1-bb6f-b39aaab17859.png)


The download from http://hypha.net/hypha.php
![Selection_680](https://user-images.githubusercontent.com/3217432/155632629-a6d8487b-8155-4562-94bd-a700392ca4b0.png)
