### ISSUE TITLE
article add image

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#39]
bij het maken van een article lukt het niet om een plaatje toe te voegen. Melding "Invalid image file, must be a valid image less than 2M" maar de plaatjes zijn niet groot. Lukt zowel niet bij .jpeg als .jpg

**Comment by giplt** [comment]
Probably same issue as #40, i.e. editor addon code for iamges and links doesn't check which instance of wymeditor is it operating from.

**Comment by tammoterhark** [comment]
Overgebracht naar hypha-improvements

**Comment by giplt** [comment]
Fixed with https://github.com/PlanBCode/hypha/commit/75b2242db7f364680c66bb8c51c87bc7ea373368
