### ISSUE TITLE
article page link does not work

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#40]
link does not become clickable

**Comment by giplt** [comment]
This has to do with multiple instances of wymeditor on one page. Fix probably has to do with passing the callback code for links and images to the right instance/iframe.

**Comment by tammoterhark** [comment]
Overgebracht naar hypha-improvements

**Comment by giplt** [comment]
Fixed with commit https://github.com/PlanBCode/hypha/commit/75b2242db7f364680c66bb8c51c87bc7ea373368
