### ISSUE TITLE
article review comments confusing

### ISSUE THREAD

**Issue by dianawi** [PlanBCode/hypha#42]
-als je als tweede reviewt krijg je twee comment windows onder elkaar, dat is verwarrend.
-er staat 'set as closed', wat doet dat? Kan dat anders omschreven worden?

**Comment by laurensmartina** [comment]
Tammo heeft hier al een verbetering in gemaakt door met kleuren en marges te werken.

**Comment by tammoterhark** [comment]
Overgebracht naar hypha-improvements

**Comment by matthijskooijman** [comment]
I think this is covered in more detail in #199, so I'm closing this one.
