### ISSUE TITLE
@import lijkt niet te werken

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#58]
Wanneer ik in hypha.css een import statement gebruik:

`@import url("css/normalize.css");`

lijkt dit niet te werken. Doe ik wat fout of is dit intentioneel?

**Comment by tammoterhark** [comment]
Yes, dat hoop ik ook te bereiken: 

/data/themes
/data/themes/default
/data/themes/koppelting
/data/themes/meetjestad
/data/themes/destadsbron

met per theme directory:
hypha.css
hypha.html
/fonts
/images
/css (voor onderliggende stylesheets)

**Comment by tammoterhark** [comment]
Maar dat kan ik niet alleen...

**Comment by tammoterhark** [comment]
Inderdaad, goede tip: aangepast dat alleen css/normalize.css geincluud kan worden.

Maar als ik met @fontface de fonts wil aanroepen in de fonts-directory, kunnen die ook niet aangeroepen worden.

Ik probeerde:
`if ($hyphaQuery == 'data/font/*.*') serveFile($hyphaQuery, false); `
maar helaas... Kun je me nog een stapje verder helpen?

**Comment by matthijskooijman** [comment]
Ik denk dat dit werkt:

    if (strpos($hyphaQuery, 'data/font/') === 0) serveFile($hyphaQuery, false);

**Comment by tammoterhark** [comment]
Code uit mail toegepast:

`if (strpos($hyphaQuery, 'data/font/') === 0) serveFile($hyphaQuery, false);`

En het werkt! Magisch! Dank.
