### ISSUE TITLE
Possibility to add extra author

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#59]
And give this co-author same rights and notifications as primary author.

**Comment by dianawi** [comment]
do you mean the review commets or the visitors' comments? In case of the last: related to #124

**Comment by matthijskooijman** [comment]
Does the author have any rights and notifications at all? Right now, I believe the author field is just a free-form textfield, and notifications are sent to all users already? And all users have the same rights, AFAICS?

Or are there plans to change this and associate a user(name) with an article as the author, and is this issue about that future situation?

**Comment by tammoterhark** [comment]
My wrong: I meant adding an author, extra to the user that defined the
page/article.

Op ma 26 nov. 2018 om 17:54 schreef Matthijs Kooijman <
notifications@github.com>:

**Comment by matthijskooijman** [comment]
Ok, but my point is that you can already do this: Just put e.g. "Matthijs Kooijman and Tammo ter Hark" in the "author" field, and this will be displayed as you entered it.

My other point was that, programatically, there is no concept of an author with extra rights or notifications, so adding a second author like this makes the second author be treated exactly the same as the first author (namely, not at all :-p).

**Comment by matthijskooijman** [comment]
If we implement #176, I suspect this is no longer needed. @tammoterhark, if you agree, could you close this?

**Comment by tammoterhark** [comment]
Right
