### ISSUE TITLE
Send notifications when guests add comments

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#60]
Zowel interne als externe commentaren

**Comment by matthijskooijman** [comment]
There are already notifications for internal comments, right?

**Comment by tammoterhark** [comment]
Yes, there are notifications:
* when article changes status (internal use)

Needed:
* notifications for author when reader comment is added
* possibility to subscribe/unsubscribe to comments
* autosubscribe when adding comment (default, possibility to switch this off)

**Comment by matthijskooijman** [comment]
This is fixed in #183 / 6bf3b52f977c4cc9628fd1d8802c6b0d71651b26
