### ISSUE TITLE
Check delete message in digest

### ISSUE THREAD

**Issue by tammoterhark** [PlanBCode/hypha#84]
Line from hypha improvements. Unsure what this means.

**Comment by matthijskooijman** [comment]
Just tested deleting a text page, which shows up in the digest:

> 26-11-18, 20:16 Matthijs Kooijman deleted the following page: en/Test

**Comment by matthijskooijman** [comment]
Articles as well:

> 26-11-18, 20:19 Matthijs Kooijman deleted the following page: en/Testarticle3

I guess this is ok, then.
